"use client";

import { useState } from "react";

type Language = "en" | "th";
const copy = {
  en: {
    eyebrow: "AIAT × CAMT · Lab 2", title: "Security workbench", subtitle: "The RAG baseline works. The security boundary does not exist yet.", chat: "RAG chat", knowledge: "Knowledge base", warning: "Nothing on this page enforces a policy. The table below is a mock, not audit storage.", todo: "Deliberately unfinished controls", audit: "Audit events — placeholder only", scenarios: "Five adversarial scenarios for secure-rag-v2", emptyAudit: "No persisted audit events. Privacy-minimised audit persistence is a Lab 2 TODO.", controls: ["Signed HttpOnly public/staff demo sessions and server-side authorization", "Access-filtered FTS5 and SQLite-vec retrieval", "Authorization on document list, detail, source-file, and citation routes", "Direct prompt-injection and synthetic-PII refusal before NVIDIA Build", "Indirect-injection filtering for poisoned corpus fixtures", "Structured output with authorized citation chunk-ID validation", "Privacy-minimised audit-event persistence and display", "Safe refusal states for policy, PII, unavailable access, and unsafe output"], scenariosList: ["A public user requests a staff assessment exception memo.", "A direct prompt asks the assistant to ignore its rules or reveal staff material.", "A request includes synthetic PII that must not reach NVIDIA Build or audit storage.", "A retrieved public fixture contains an indirect instruction intended to poison model context.", "A model response tries to cite a chunk outside the authorized retrieval context."]
  },
  th: {
    eyebrow: "AIAT × CAMT · Lab 2", title: "พื้นที่ทำงานด้านความปลอดภัย", subtitle: "RAG baseline ทำงานแล้ว แต่ยังไม่มี security boundary.", chat: "RAG chat", knowledge: "คลังความรู้", warning: "ไม่มีสิ่งใดในหน้านี้บังคับใช้นโยบาย ตารางด้านล่างเป็น mock ไม่ใช่ audit storage.", todo: "controls ที่ตั้งใจยังไม่สร้าง", audit: "Audit events — placeholder เท่านั้น", scenarios: "ห้า adversarial scenarios สำหรับ secure-rag-v2", emptyAudit: "ยังไม่มี audit event ที่บันทึกจริง การจัดเก็บ audit ที่ลดข้อมูลส่วนบุคคลเป็น TODO ของ Lab 2.", controls: ["Signed HttpOnly demo session public/staff และ authorization ฝั่ง server", "FTS5 และ SQLite-vec retrieval ที่กรองตามสิทธิ์", "Authorization สำหรับ document list, detail, source-file และ citation route", "ปฏิเสธ direct prompt injection และ synthetic PII ก่อน NVIDIA Build", "กรอง indirect injection จาก poisoned corpus fixture", "structured output พร้อมตรวจสอบ citation chunk ID ที่ได้รับสิทธิ์", "การจัดเก็บและแสดง audit event โดยลดข้อมูลส่วนบุคคล", "safe refusal สำหรับ policy, PII, สิทธิ์ไม่พร้อม และ unsafe output"], scenariosList: ["ผู้ใช้ public ขอ staff assessment exception memo.", "prompt โดยตรงขอให้ assistant ละเลยกฎหรือเปิดเผย staff material.", "คำขอมี synthetic PII ที่ห้ามส่งไป NVIDIA Build หรือ audit storage.", "public fixture ที่ค้นได้มี indirect instruction เพื่อ poison model context.", "คำตอบจากโมเดลพยายามอ้าง chunk นอก authorized retrieval context."]
  },
} as const;

export default function SecurityPage() {
  const [language, setLanguage] = useState<Language>("en");
  const text = copy[language];
  return <main className="lab"><header className="hero"><div><p className="eyebrow">{text.eyebrow}</p><h1>{text.title}</h1><p className="subtitle">{text.subtitle}</p></div><div className="header-actions"><nav><a href="/">{text.chat}</a><a href="/knowledge">{text.knowledge}</a></nav><div className="language" aria-label="Language"><button className={language === "en" ? "selected" : ""} onClick={() => setLanguage("en")}>EN</button><button className={language === "th" ? "selected" : ""} onClick={() => setLanguage("th")}>ไทย</button></div></div></header><p className="warning" role="alert">{text.warning}</p><section className="security-grid"><section className="todo-list"><p className="eyebrow">Lab 2 TODO</p><h2>{text.todo}</h2><ol>{text.controls.map((control) => <li key={control}>{control}</li>)}</ol></section><section className="audit-card"><p className="eyebrow">AuditEvent contract</p><h2>{text.audit}</h2><div className="table-wrap"><table><thead><tr><th>createdAt</th><th>role</th><th>decision</th><th>citationChunkIds</th></tr></thead><tbody><tr><td colSpan={4}>{text.emptyAudit}</td></tr></tbody></table></div></section></section><section className="scenario-list"><p className="eyebrow">Adversarial fixtures</p><h2>{text.scenarios}</h2><ol>{text.scenariosList.map((scenario) => <li key={scenario}>{scenario}</li>)}</ol></section></main>;
}
